#!/usr/bin/env python3
"""
nico-dev — Build nico-admin-cli and machine-a-tron (MAT) from source

Builds the operator CLI tools from infra-controller-core using cargo.
Reads infra-controller-core path from site yaml (nico_mac_folder or nico_vm_folder).
Optionally installs them to a directory on $PATH.

Crates built:
  nico-admin-cli    — operator CLI for day-1 site setup, credential management
  machine-a-tron    — managed host BMC/DHCP simulator (MAT)

machine-a-tron runs on the VM (not the host) — it needs the br-<dc>-internet
interface which lives inside the VM. It is therefore built FOR LINUX inside
a rust container (docker — already a nico-dev prerequisite): the
linux/<host-arch> container is native (arm64 or amd64), so this is a plain
Linux cargo build with zero assumptions about the host's rust setup. The
rust image version is read from the repo's own rust-toolchain.toml. The
binary is delivered through the share to {site}/mat/machine-a-tron, where
run-mat.sh (generated by configure-clis.py) installs and setcaps it VM-side.

Host CLIs (nico-admin-cli, nicocli) — explicit platform branch:
  macOS: built with the host's cargo / go (a Mac needs Mach-O binaries).
  Linux: built in containers too (rust:<repo version>, golang:<go.mod
         version>) — a Linux host runs the ELF directly, so no rustup or Go
         installation is needed on the box.

Usage:
  ./build-nico-clis.py ~/sites/dev
  ./build-nico-clis.py ~/sites/dev --install-to ~/.local/bin
  ./build-nico-clis.py ~/sites/dev --admin-cli-only
  ./build-nico-clis.py ~/sites/dev --mat-only
  ./build-nico-clis.py ~/sites/dev --mat-only --repo ~/projects/nico-mat \\
                                   --out-dir ~/projects/nico-mat/out
    # feature-worktree build: --out-dir is REQUIRED with --repo so an
    # experimental binary never overwrites the baseline in {site}/mat/
"""

import argparse
import platform
import os
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print('Error: pyyaml not installed. Run: pip3 install pyyaml')
    sys.exit(1)


DOCKER_ARCH = 'arm64' if platform.machine() in ('arm64', 'aarch64') else 'amd64'
ELF_MACHINE = 'aarch64' if platform.machine() in ('arm64', 'aarch64') else 'x86-64'

# Where the HOST-side CLIs (nico-admin-cli, nicocli) get built — an explicit
# platform branch, never a fallback:
#   Darwin: the host toolchains (cargo, go). A Mac needs Mach-O binaries and
#           a container can only produce Linux ones.
#   Linux:  inside containers (rust:<repo version>, golang:<go.mod version>).
#           A Linux host runs a container-built ELF directly, so no rustup/Go
#           on the box — the same route machine-a-tron already takes.
HOST_OS = platform.system()
if HOST_OS not in ('Darwin', 'Linux'):
    print(f'Error: unsupported host platform {HOST_OS} (Darwin or Linux)', file=sys.stderr)
    sys.exit(1)
HOST_UID, HOST_GID = os.getuid(), os.getgid()


def resolve_site(arg):
    p = Path(arg).expanduser()
    if p.is_dir():
        yamls = [f for f in p.glob('*.yaml') if not f.stem.endswith('-mac') and '.kubeconfig' not in f.name]
        if not yamls:
            print(f'Error: no site yaml in {p}', file=sys.stderr); sys.exit(1)
        if len(yamls) > 1:
            print(f'Error: multiple yamls in {p}', file=sys.stderr); sys.exit(1)
        return str(yamls[0])
    return str(p)


def parse_args():
    p = argparse.ArgumentParser(
        description='Build nico-admin-cli and machine-a-tron from source',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument('site', help='Site folder (e.g. ~/sites/dev) or yaml file')
    p.add_argument('--install-to', default=None, metavar='DIR',
                   help='Copy built binaries to this directory (e.g. ~/.local/bin)')
    p.add_argument('--admin-cli-only', action='store_true',
                   help='Build only nico-admin-cli')
    p.add_argument('--mat-only', action='store_true',
                   help='Build only machine-a-tron')
    p.add_argument('--repo', default=None, metavar='DIR',
                   help='Build from this nico repo checkout instead of the site '
                        'yaml one (e.g. a feature-branch worktree)')
    p.add_argument('--out-dir', default=None, metavar='DIR',
                   help='Deliver the machine-a-tron binary here instead of '
                        '{site}/mat/ — keeps experimental builds from '
                        'overwriting the baseline the site uses')
    p.add_argument('--skip-nicocli', action='store_true',
                   help='Skip building nicocli (the Go REST CLI from rest-api/cli)')
    args = p.parse_args()
    if args.repo and not args.out_dir:
        p.error('--repo requires --out-dir: a feature build must not '
                'silently overwrite the baseline binary in {site}/mat/ '
                '(copy it there deliberately when ready to test)')
    return args


def load_cfg(path):
    with open(path) as f:
        return yaml.safe_load(f)


def resolve_repo(cfg):
    """Resolve the nico repo: nico_repo_folder joined onto whichever share
    root is accessible from here (Mac first, then VM)."""
    repo_folder = cfg.get('nico_repo_folder', 'infra-controller-core')
    nico_mac = cfg.get('nico_mac_folder', '')
    nico_vm  = cfg.get('nico_vm_folder', '')
    if nico_mac and Path(nico_mac).expanduser().exists():
        return str(Path(nico_mac).expanduser() / repo_folder)
    if nico_vm and Path(nico_vm).expanduser().exists():
        return str(Path(nico_vm).expanduser() / repo_folder)
    return cfg.get('infra_controller_repo', '')


def run(cmd, cwd=None, label=''):
    print(f'  $ {" ".join(str(c) for c in cmd)}')
    r = subprocess.run(cmd, cwd=cwd)
    if r.returncode != 0:
        raise RuntimeError(f'{label or cmd[0]} failed (exit {r.returncode})')


def build_crate(repo_path, crate_name, label):
    print(f'\n── Building {label} ──────────────────────────────────')
    print(f'  First build: ~5-10 min  |  incremental: ~1 min')
    print(f'  Cargo output follows — wait for the ✓ line below.')
    print()
    run(
        ['cargo', 'build', '--release', '-p', crate_name],
        cwd=repo_path,
        label=f'cargo build {crate_name}',
    )
    binary = Path(repo_path) / 'target' / 'release' / label
    if not binary.exists():
        binary = Path(repo_path) / 'target' / 'release' / crate_name
    if not binary.exists():
        raise RuntimeError(f'Binary not found after build. Expected: {binary}')
    size_mb = binary.stat().st_size / 1024 / 1024
    print(f'  ✓ {binary}  ({size_mb:.0f} MB)')
    return binary


def _repo_rust_version(repo_path):
    """The rust version the REPO wants (rust-toolchain.toml channel)."""
    import re
    p = Path(repo_path) / 'rust-toolchain.toml'
    if p.exists():
        m = re.search(r'channel\s*=\s*"([^"]+)"', p.read_text())
        if m:
            return m.group(1)
    return '1'  # latest stable — only if the repo stops pinning


def _worktree_git_mount(repo_path):
    """Extra -v args so git works when repo_path is a git WORKTREE.

    A worktree's .git is a FILE pointing (absolute host path) into the main
    clone's .git/worktrees/<name>. Build scripts that embed git info would
    fail inside the container without it — mount the main .git dir read-only
    at the identical path so the pointer resolves.
    """
    dotgit = Path(repo_path) / '.git'
    if not dotgit.is_file():
        return []
    gitdir = dotgit.read_text().strip().removeprefix('gitdir:').strip()
    main_git = gitdir.split('/worktrees/')[0]
    return ['-v', f'{main_git}:{main_git}:ro']


def _docker_required(what):
    if subprocess.run(['docker', 'info'], capture_output=True).returncode != 0:
        hint = ('Start colima (or Docker Desktop) and retry.' if HOST_OS == 'Darwin'
                else 'sudo systemctl start docker; sudo usermod -aG docker $USER (relogin).')
        print(f'Error: docker daemon not reachable — {what} runs in a container.\n'
              f'  {hint}', file=sys.stderr)
        sys.exit(1)


def container_cargo_build(repo_path, crate, binary, dest_dir, label):
    """Build one workspace crate inside a linux/<host-arch> rust container and
    deliver the release binary to dest_dir, owned by the invoking user.

    The container image is rust:<repo's rust-toolchain.toml version> plus the
    system packages the workspace's build scripts need (protoc for
    carbide-rpc, cmake/ssl — the set the repo's own build container installs).
    Built once per rust version, cached. Named docker volumes hold the target
    dir and crate cache, so rebuilds are incremental across crates.
    """
    rust_ver = _repo_rust_version(repo_path)
    image = f'nico-mat-build:{rust_ver}'   # historical name; shared by all crates
    print(f'\n── Building {label} (Linux {DOCKER_ARCH}, in {image}) ─────')
    _docker_required(f'the {label} build')

    r = subprocess.run(['docker', 'image', 'inspect', image], capture_output=True)
    if r.returncode != 0:
        print(f'  Creating build image {image} (one-time per rust version)...')
        dockerfile = (
            f'FROM rust:{rust_ver}\n'
            'RUN apt-get update && DEBIAN_FRONTEND=noninteractive '
            'apt-get install -y --no-install-recommends '
            'protobuf-compiler libprotobuf-dev cmake pkg-config libssl-dev '
            '&& rm -rf /var/lib/apt/lists/*\n'
        )
        r = subprocess.run(['docker', 'build', '--platform', f'linux/{DOCKER_ARCH}',
                            '-t', image, '-f', '-', '.'],
                           input=dockerfile, text=True)
        if r.returncode != 0:
            raise RuntimeError(f'failed to build {image}')

    dest_dir = Path(dest_dir).expanduser()
    dest_dir.mkdir(parents=True, exist_ok=True)

    print(f'  First build: ~10-20 min (pulls {image} once)  |  incremental: ~1-2 min')
    run(['docker', 'run', '--rm', '--platform', f'linux/{DOCKER_ARCH}',
         '-v', f'{Path(repo_path).resolve()}:/src']
        + _worktree_git_mount(repo_path) +
        ['-v', 'nico-mat-target:/target',
         '-v', 'nico-mat-cargo-registry:/usr/local/cargo/registry',
         '-v', f'{dest_dir.resolve()}:/out',
         '-w', '/src',
         '-e', 'CARGO_TARGET_DIR=/target',
         # same knob the nico image build uses: without it the workspace's
         # release profile embeds debug info → a 229 MB binary vs ~40 MB
         '-e', 'CARGO_PROFILE_RELEASE_DEBUG=false',
         image, 'sh', '-c',
         f'cargo build --release -p {crate} '
         f'&& cp /target/release/{binary} /out/ '
         # the container runs as root; on a Linux host (virtiofs/bind mounts
         # keep real uids) the delivered file would otherwise be root-owned
         f'&& chown {HOST_UID}:{HOST_GID} /out/{binary}'],
        label=f'container build {crate}')

    dest = dest_dir / binary
    if not dest.exists():
        raise RuntimeError(f'Binary not delivered: {dest}')
    r = subprocess.run(['file', str(dest)], capture_output=True, text=True)
    if 'ELF' not in r.stdout or ELF_MACHINE not in r.stdout:
        raise RuntimeError(f'Unexpected binary format (want ELF {ELF_MACHINE}): '
                           f'{r.stdout.strip()}')
    dest.chmod(0o755)
    size_mb = dest.stat().st_size / 1024 / 1024
    print(f'  ✓ {dest}  ({size_mb:.0f} MB, ELF {ELF_MACHINE} — verified)')
    return dest


def build_mat_container(repo_path, site_folder, out_dir=None):
    """Build machine-a-tron for the VM inside a Linux rust container.

    MAT must run ON THE VM (it binds br-<dc>-internet, which only exists
    there, and its interface plumbing is Linux-only) — a native Mac build is
    a Mach-O binary the VM cannot execute. Building in a linux/<host-arch>
    container is a plain native Linux build on either host: no zig, no
    rustup targets, no assumptions about the host's toolchain. Delivery is
    via the share: the binary lands in {site}/mat/, which the VM sees under
    its mount; run-mat.sh installs + setcaps it VM-side.
    """
    dest_dir = Path(out_dir).expanduser() if out_dir else Path(site_folder) / 'mat'
    dest = container_cargo_build(repo_path, 'carbide-machine-a-tron',
                                 'machine-a-tron', dest_dir, 'machine-a-tron')
    print(f'  Delivered via the share — run-mat.sh on the VM installs it locally.')
    return dest


def _repo_go_version(repo_path):
    """major.minor from rest-api/go.mod (the golang image tag to build with)."""
    import re
    p = Path(repo_path) / 'rest-api' / 'go.mod'
    m = re.search(r'^go\s+(\d+\.\d+)', p.read_text(), re.M) if p.exists() else None
    return m.group(1) if m else '1'


def build_nicocli_container(repo_path, install_dir):
    """Linux host: build nicocli in a golang:<go.mod version> container, deliver
    to install_dir owned by the invoking user. Module and build caches live in
    named volumes so rebuilds are incremental."""
    go_ver = _repo_go_version(repo_path)
    image = f'golang:{go_ver}'
    print(f'\n── Building nicocli (Go, rest-api/cli — Linux {DOCKER_ARCH}, in {image}) ──')
    _docker_required('the nicocli build')
    install_dir = Path(install_dir).expanduser()
    install_dir.mkdir(parents=True, exist_ok=True)
    run(['docker', 'run', '--rm', '--platform', f'linux/{DOCKER_ARCH}',
         '-v', f'{Path(repo_path).resolve()}:/src']
        + _worktree_git_mount(repo_path) +
        ['-v', 'nico-go-mod-cache:/go/pkg/mod',
         '-v', 'nico-go-build-cache:/root/.cache/go-build',
         '-v', f'{install_dir.resolve()}:/out',
         '-w', '/src/rest-api',
         image, 'sh', '-c',
         'make nico-cli INSTALL_DIR=/out '
         f'&& chown {HOST_UID}:{HOST_GID} /out/nicocli'],
        label='container build nicocli')
    return install_dir / 'nicocli'


def install_binary(binary, install_dir):
    dest = Path(install_dir).expanduser() / binary.name
    dest.parent.mkdir(parents=True, exist_ok=True)
    import shutil
    shutil.copy2(str(binary), str(dest))
    dest.chmod(0o755)
    print(f'  Installed: {dest}')
    return dest


def main():
    args        = parse_args()
    site_yaml   = resolve_site(args.site)
    site_folder = Path(site_yaml).expanduser().parent
    cfg         = load_cfg(site_yaml)
    repo        = args.repo or resolve_repo(cfg)

    if not repo:
        print('Error: could not find infra-controller-core repo.', file=sys.stderr)
        print('  Set nico_mac_folder or nico_vm_folder in site yaml.', file=sys.stderr)
        sys.exit(1)
    repo_path = Path(repo).expanduser()
    if not repo_path.exists():
        print(f'Error: repo not found: {repo}', file=sys.stderr)
        sys.exit(1)

    build_admin = not args.mat_only
    build_mat   = not args.admin_cli_only

    print('nico-dev — Build CLI Tools')
    print(f'  repo      : {repo_path}')
    print(f'  building  : '
          + ', '.join(filter(None, [
              'nico-admin-cli' if build_admin else '',
              'machine-a-tron' if build_mat else '',
          ])))
    if args.install_to:
        print(f'  install-to: {args.install_to}')
    print()

    built = {}

    # ── Build nico-admin-cli (host binary) ────────────────────────────────────
    if build_admin:
        if HOST_OS == 'Darwin':
            # Mach-O for the Mac: only the host's cargo can produce it
            binary = build_crate(repo_path, 'nico-admin-cli', 'nico-admin-cli')
        else:
            # Linux host runs a container-built ELF directly — no rustup needed.
            # Delivered into the repo's target/release like a host build would.
            binary = container_cargo_build(repo_path, 'nico-admin-cli', 'nico-admin-cli',
                                           repo_path / 'target' / 'release',
                                           'nico-admin-cli')
        built['nico-admin-cli'] = binary
        if args.install_to:
            built['nico-admin-cli'] = install_binary(binary, args.install_to)

    # ── Build machine-a-tron (cross-compiled for the VM) ──────────────────────
    if build_mat:
        built['machine-a-tron'] = build_mat_container(repo_path, site_folder,
                                                      out_dir=args.out_dir)
        # note: never --install-to'd on the Mac — it is a Linux binary

    # ── Build nicocli (Go REST CLI — the 4th developer surface) ───────────────
    rest_enabled = cfg.get('nico-system', {}).get('rest', {}).get('enabled', True)
    rest_dir = repo_path / 'rest-api'
    if args.skip_nicocli or args.admin_cli_only or args.mat_only or not rest_enabled:
        print('\n── nicocli skipped ──')
    elif not rest_dir.is_dir():
        print(f'\n  Warning: rest-api/ not in checkout — nicocli skipped')
    else:
        install_dir = Path(args.install_to).expanduser() if args.install_to \
                      else rest_dir / 'build' / 'binaries'
        if HOST_OS == 'Darwin':
            r = subprocess.run(['go', 'version'], capture_output=True)
            if r.returncode != 0:
                print('\nError: Go toolchain required for nicocli (brew install go)',
                      file=sys.stderr)
                sys.exit(1)
            print('\n── Building nicocli (Go, rest-api/cli) ─────────────')
            run(['make', '-C', str(rest_dir), 'nico-cli',
                 f'INSTALL_DIR={install_dir}'], label='make nico-cli')
        else:
            build_nicocli_container(repo_path, install_dir)
        nicocli = install_dir / 'nicocli'
        if nicocli.exists():
            built['nicocli'] = nicocli
            print(f'  ✓ {nicocli}  ({nicocli.stat().st_size / 1024 / 1024:.0f} MB)')
        else:
            print(f'  Warning: nicocli not found at {nicocli} after build')

    # ── Summary ───────────────────────────────────────────────────────────────
    print()
    print('=' * 55)
    print('Build complete.')
    print()
    for name, path in built.items():
        print(f'  {name}: {path}')
    print()

    if args.install_to:
        install_dir = Path(args.install_to).expanduser()
        print(f'Binaries installed to {install_dir}.')
        print(f'Ensure {install_dir} is in $PATH:')
        print(f'  export PATH="{install_dir}:$PATH"')
    else:
        print('Binaries are in target/release/. Add to PATH or use --install-to.')
        target = repo_path / 'target' / 'release'
        print(f'  export PATH="{target}:$PATH"')

    print()
    print('Next: configure certs and run scripts:')
    print(f'  {Path(__file__).parent / "configure-clis.py"} {Path(args.site).expanduser()}')


if __name__ == '__main__':
    main()
