#!/usr/bin/env python3
"""
nico-dev — Deploy Nico helm stack on the dev kubeadm cluster.

Runs on the Mac (canonical) or the VM — helm/kubectl reach the cluster via the
site kubeconfig either way. The cluster pulls images from the Mac registry
(192.168.64.1:5000 as seen from the VM).

Helm values are generated by generate_dev_values.py into {site}/dev-values/
on every run (cert-manager.yaml, vault.yaml, eso.yaml, zalando-postgres-op.yaml,
nico-prereqs.yaml, nico.yaml — nico.yaml embeds the nico-api siteConfig TOML).

Usage:
  python3 deploy-dev-nico.py <site> --tag <tag>
  python3 deploy-dev-nico.py <site> --skip-to <release>   # resume from a release
  python3 deploy-dev-nico.py <site> --only <release>      # redeploy one release

Release order:
  local-path-provisioner → cert-manager → vault → external-secrets
  → postgres-operator → nico-prereqs → nico

Recovery:
  Stuck helm releases (pending-install/pending-upgrade/failed) are healed
  automatically before each install. Do NOT delete the nico-system namespace
  to recover — it holds the helm release state for nico-prereqs AND nico;
  deleting it destroys both and races against namespace termination. Use
  --only/--skip-to instead.
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

try:
    import yaml
except ImportError:
    print('Error: pyyaml not installed. Run: sudo apt install python3-yaml')
    sys.exit(1)


DEPLOY_ORDER = [
    'local-path-provisioner',
    'cert-manager',
    'vault',
    'external-secrets',
    'postgres-operator',
    'nico-prereqs',
    'nico',
    # NICo REST stack (nico-system.rest.enabled in the site yaml, default true):
    'rest-postgres',
    'keycloak',
    'temporal',
    'nico-rest',
    'nico-rest-site-agent',
]

# Steps installed as helm releases: DEPLOY_ORDER entry → (release, namespace).
# rest-postgres (kustomize) and keycloak (kubectl apply) are workload-checked.
HELM_RELEASE_OF = {
    'local-path-provisioner': ('local-path-provisioner', 'local-path-storage'),
    'cert-manager':           ('cert-manager',           'cert-manager'),
    'vault':                  ('vault',                  'vault'),
    'external-secrets':       ('external-secrets',       'external-secrets'),
    'postgres-operator':      ('postgres-operator',      'postgres'),
    'nico-prereqs':           ('nico-prereqs',           'nico-system'),
    'nico':                   ('nico',                   'nico-system'),
    'temporal':               ('temporal',               'temporal'),
    'nico-rest':              ('nico-rest',              'nico-rest'),
    'nico-rest-site-agent':   ('nico-rest-site-agent',   'nico-rest'),
}
_REST_STEPS = {'rest-postgres', 'keycloak', 'temporal', 'nico-rest',
               'nico-rest-site-agent'}


def resolve_site(arg):
    p = Path(arg).expanduser()
    if p.is_dir():
        yamls = [f for f in p.glob('*.yaml') if '.kubeconfig' not in f.name]
        if not yamls:
            print(f'Error: no site yaml in {p}', file=sys.stderr); sys.exit(1)
        if len(yamls) > 1:
            print(f'Error: multiple yamls in {p}', file=sys.stderr); sys.exit(1)
        return str(yamls[0]), str(p)
    return str(p), str(Path(p).parent)


def run(cmd, env=None, check=True, capture=False, stdin=None, timeout=600):
    e = {**os.environ, **(env or {})}
    r = subprocess.run(cmd, capture_output=capture, text=True,
                       env=e, input=stdin, timeout=timeout)
    if check and r.returncode != 0:
        print(f'  ! failed: {(r.stderr or r.stdout or "").strip()}', file=sys.stderr)
        sys.exit(1)
    return r


def helm(args, kubeconfig, timeout=600):
    return run(['helm'] + args, env={'KUBECONFIG': kubeconfig}, timeout=timeout)


def kubectl(args, kubeconfig, capture=True, check=True, stdin=None):
    return run(['kubectl'] + args, env={'KUBECONFIG': kubeconfig},
               capture=capture, check=check, stdin=stdin)


def heal_stuck_release(release, ns, kubeconfig):
    """Clear a helm release stuck in a pending/failed state.

    An interrupted helm run leaves the release secret in pending-install or
    pending-upgrade; the next 'helm upgrade --install' then fails with
    'another operation is in progress'. Deleting the pending secret rolls the
    release back to its last completed revision (or to absent, for a first
    install) so the retry proceeds — this is the documented recovery that
    users previously had to run by hand.
    """
    r = run(['helm', 'status', release, '-n', ns],
            env={'KUBECONFIG': kubeconfig}, check=False, capture=True)
    if r.returncode != 0:
        return   # release doesn't exist — nothing to heal
    for line in r.stdout.splitlines():
        if line.startswith('STATUS:'):
            status = line.split(':', 1)[1].strip()
            if status in ('pending-install', 'pending-upgrade', 'pending-rollback',
                          'failed', 'uninstalling'):
                print(f'  healing stuck release {release} (status: {status})')
                kubectl(['delete', 'secret', '-n', ns,
                         '-l', f'owner=helm,name={release},status={status}'],
                        kubeconfig, check=False)
            break


def ensure_nico_namespace(kubeconfig):
    """Create/adopt the nico-system namespace, safely.

    Handles the exists/absent flip-flop users hit during recovery:
    - If the namespace is Terminating (a previous recovery deleted it), WAIT
      for the deletion to finish — creating or installing into a Terminating
      namespace fails with confusing errors on both sides.
    - Create it if absent (idempotent), then apply helm ownership labels so
      the nico-prereqs chart can adopt it (helm refuses to adopt an unlabeled
      pre-existing namespace).
    """
    deadline = time.time() + 180
    warned = False
    while time.time() < deadline:
        r = kubectl(['get', 'namespace', 'nico-system',
                     '-o', 'jsonpath={.status.phase}'], kubeconfig, check=False)
        phase = r.stdout.strip()
        if phase != 'Terminating':
            break
        if not warned:
            print('  nico-system namespace is Terminating — waiting for deletion to finish...')
            warned = True
        time.sleep(5)
    else:
        print('Error: nico-system namespace stuck Terminating after 180s.', file=sys.stderr)
        print('  Inspect: kubectl get namespace nico-system -o yaml (look at finalizers)',
              file=sys.stderr)
        sys.exit(1)

    kubectl(['create', 'namespace', 'nico-system'], kubeconfig, check=False)
    kubectl(['label', 'namespace', 'nico-system',
             'app.kubernetes.io/managed-by=Helm', '--overwrite'], kubeconfig, check=False)
    kubectl(['annotate', 'namespace', 'nico-system',
             'meta.helm.sh/release-name=nico-prereqs',
             'meta.helm.sh/release-namespace=nico-system', '--overwrite'],
            kubeconfig, check=False)


def preflight_skipped_prereqs(target, vault_mode, rest_enabled, kubeconfig):
    """--skip-to/--only assume every earlier step is deployed AND healthy.

    Verify that instead of assuming it: a missing/failed helm release, an
    uninitialized vault, or a crashlooping pod in a skipped step makes the
    resumed deploy fail later in a far more confusing way. Hard-errors with
    cleanup guidance.
    """
    import json as _json

    prereqs = DEPLOY_ORDER[:DEPLOY_ORDER.index(target)]
    if not prereqs:
        return
    print(f'\nPreflight: verifying {len(prereqs)} skipped prerequisite steps...')

    r = run(['helm', 'list', '-A', '-o', 'json'],
            env={'KUBECONFIG': kubeconfig}, capture=True)
    try:
        status_of = {rel['name']: rel['status']
                     for rel in _json.loads(r.stdout or '[]')}
    except ValueError:
        status_of = {}

    problems   = []
    namespaces = set()
    for step in prereqs:
        if step in _REST_STEPS and not rest_enabled:
            continue
        if step in HELM_RELEASE_OF:
            rel, ns = HELM_RELEASE_OF[step]
            namespaces.add(ns)
            st = status_of.get(rel)
            if st is None:
                problems.append(f'{step}: helm release "{rel}" not found — '
                                f'skipped but never deployed')
            elif st != 'deployed':
                problems.append(f'{step}: helm release "{rel}" is "{st}" '
                                f'(expected "deployed")')
        elif step == 'rest-postgres':
            namespaces.add('postgres')
            if kubectl(['get', 'statefulset', 'postgres', '-n', 'postgres'],
                       kubeconfig, check=False).returncode != 0:
                problems.append('rest-postgres: statefulset postgres/postgres '
                                'not found — skipped but never deployed')
        elif step == 'keycloak':
            namespaces.add('nico-rest')
            if kubectl(['get', 'deployment', 'keycloak', '-n', 'nico-rest'],
                       kubeconfig, check=False).returncode != 0:
                problems.append('keycloak: deployment nico-rest/keycloak '
                                'not found — skipped but never deployed')

    if 'vault' in prereqs and vault_mode == 'file':
        if kubectl(['get', 'secret', 'vault-init-keys', '-n', 'vault'],
                   kubeconfig, check=False).returncode != 0:
            problems.append('vault: vault-init-keys secret missing — vault '
                            'was never initialized (file mode)')

    # Broken pods anywhere in the skipped steps' namespaces
    bad_states = ('CrashLoopBackOff', 'Error', 'ImagePullBackOff',
                  'ErrImagePull', 'CreateContainerConfigError', 'Failed')
    for ns in sorted(namespaces):
        r = kubectl(['get', 'pods', '-n', ns, '--no-headers'],
                    kubeconfig, check=False)
        for line in (r.stdout or '').splitlines():
            # Pods of the TARGET step share namespaces with skipped steps
            # (e.g. nico-rest-site-agent-0 in nico-rest); their brokenness is
            # what the resume is about to fix — don't block on it.
            if line.split()[0].startswith(target):
                continue
            if any(s in line for s in bad_states):
                problems.append(f'broken pod in skipped step namespace '
                                f'"{ns}": {" ".join(line.split()[:3])}')

    if problems:
        print('\nError: --skip-to/--only requires every skipped step to be '
              'healthy, but:', file=sys.stderr)
        for p in problems:
            print(f'  ✗ {p}', file=sys.stderr)
        print('\nClean up first:', file=sys.stderr)
        print('  - missing/pending/failed releases: re-run WITHOUT '
              '--skip-to/--only — already-deployed\n    releases are fast '
              'no-ops and pending-* states heal automatically', file=sys.stderr)
        print('  - broken pods: kubectl describe/logs them before '
              'redeploying', file=sys.stderr)
        print('  - never delete the nico-system namespace (helm release '
              'state lives there)', file=sys.stderr)
        sys.exit(1)
    print('  skipped prerequisites healthy ✓')


def ensure_vault_initialized(kubeconfig):
    """Initialize Vault (file mode) on first deploy; return root token.

    Idempotent: if already initialized, reads the token from the vault-init-keys
    k8s secret.  On first run: runs vault operator init, stores the single unseal
    key + root token in vault-init-keys, and immediately unseals.  After that the
    vault-unsealer sidecar container handles unsealing on every pod restart.
    """
    import base64
    import json as _json

    vault_ns  = 'vault'
    vault_pod = 'vault-0'

    # Wait for the Vault pod to reach Running state
    print('  Waiting for Vault pod...')
    deadline = time.time() + 120
    while time.time() < deadline:
        r = kubectl(['get', 'pod', vault_pod, '-n', vault_ns,
                     '-o', 'jsonpath={.status.phase}'], kubeconfig, check=False)
        if r.stdout.strip() == 'Running':
            break
        time.sleep(5)
    else:
        print('  Warning: Vault pod not Running after 2 min — proceeding anyway')

    # Check initialization state
    r = kubectl(['exec', '-n', vault_ns, vault_pod, '-c', 'vault', '--',
                 'vault', 'status', '-format=json'], kubeconfig, check=False)
    try:
        status = _json.loads(r.stdout)
        initialized = status.get('initialized', False)
    except Exception:
        initialized = False

    if initialized:
        # Already initialized — read token from persisted secret
        r = kubectl(['get', 'secret', 'vault-init-keys', '-n', vault_ns,
                     '-o', 'jsonpath={.data.root_token}'], kubeconfig, check=False)
        if r.returncode == 0 and r.stdout.strip():
            token = base64.b64decode(r.stdout.strip()).decode()
            print('  Vault already initialized ✓')
            return token
        print('  Warning: vault-init-keys secret not found — falling back to "root"')
        return 'root'

    # First initialization
    print('  Initializing Vault (first time)...')
    r = kubectl(['exec', '-n', vault_ns, vault_pod, '-c', 'vault', '--',
                 'vault', 'operator', 'init',
                 '-key-shares=1', '-key-threshold=1', '-format=json'], kubeconfig)
    init_data  = _json.loads(r.stdout)
    unseal_key = init_data['unseal_keys_b64'][0]
    root_token = init_data['root_token']

    # Persist keys — the vault-unsealer sidecar reads unseal_key on every restart
    kubectl(['create', 'secret', 'generic', 'vault-init-keys', '-n', vault_ns,
             f'--from-literal=unseal_key={unseal_key}',
             f'--from-literal=root_token={root_token}'], kubeconfig)
    print('  Vault initialized, keys stored in vault-init-keys secret ✓')

    # Unseal immediately (sidecar takes up to 60s to pick up the new secret volume)
    kubectl(['exec', '-n', vault_ns, vault_pod, '-c', 'vault', '--',
             'vault', 'operator', 'unseal', unseal_key], kubeconfig)
    print('  Vault unsealed ✓')

    return root_token


def wait_vault_ready(kubeconfig, timeout=120):
    """Hard gate: Vault must be initialized AND unsealed before anything
    consumes it (nico-prereqs' vault-pki-config job is the first consumer).

    Covers the OnDelete pod roll: a restarted vault-0 comes up sealed and
    the unsealer sidecar can take up to ~70s to catch it (secret volume
    propagation + 10s poll loop).
    """
    import json as _json
    print('  Waiting for Vault to be initialized + unsealed...')
    deadline = time.time() + timeout
    last = ''
    while time.time() < deadline:
        r = kubectl(['exec', '-n', 'vault', 'vault-0', '-c', 'vault', '--',
                     'vault', 'status', '-format=json'], kubeconfig, check=False)
        try:
            st = _json.loads(r.stdout)
            last = f'initialized={st.get("initialized")} sealed={st.get("sealed")}'
            if st.get('initialized') and not st.get('sealed'):
                print(f'  Vault ready ✓ ({last})')
                return
        except ValueError:
            last = (r.stderr or r.stdout or 'no response').strip()[:120]
        time.sleep(5)
    print(f'  Error: Vault not ready after {timeout}s ({last})', file=sys.stderr)
    print('  Diagnose: kubectl get pods -n vault; '
          'kubectl logs vault-0 -n vault -c vault', file=sys.stderr)
    sys.exit(1)


def ensure_ssh_host_key(ns, kubeconfig):
    """Pre-create ssh-host-key secret in OpenSSH format before nico-prereqs install.

    helm genPrivateKey produces PKCS#8 ("BEGIN PRIVATE KEY") but ssh-console-rs
    requires OpenSSH format ("BEGIN OPENSSH PRIVATE KEY").  ssh-keygen -t ed25519
    always writes OpenSSH format.  Idempotent: skips if the secret already exists.
    """
    r = kubectl(['get', 'secret', 'ssh-host-key', '-n', ns], kubeconfig, check=False)
    if r.returncode == 0:
        print('  ssh-host-key already exists — skipping')
        return

    import tempfile
    with tempfile.TemporaryDirectory() as tmpdir:
        keyfile = f'{tmpdir}/ssh_host_ed25519_key'
        run(['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', keyfile, '-C', '', '-q'])
        kubectl(['create', 'secret', 'generic', 'ssh-host-key',
                 '-n', ns,
                 f'--from-file=ssh_host_ed25519_key={keyfile}',
                 f'--from-file=ssh_host_ed25519_key_pub={keyfile}.pub'],
                kubeconfig)
        kubectl(['label', 'secret', 'ssh-host-key', '-n', ns,
                 'app.kubernetes.io/managed-by=Helm', '--overwrite'], kubeconfig)
        kubectl(['annotate', 'secret', 'ssh-host-key', '-n', ns,
                 'meta.helm.sh/release-name=nico-prereqs',
                 'meta.helm.sh/release-namespace=nico-system', '--overwrite'], kubeconfig)
    print('  ssh-host-key created (OpenSSH format) ✓')


def patch_allow_insecure_discovery(ns, kubeconfig):
    """Prepend allow_insecure_discovery=true before the first [section] in nico-api config."""
    cm  = 'nico-api-config-files'
    add = 'allow_insecure_discovery = true\n'

    r = subprocess.run(
        ['kubectl', '--kubeconfig', kubeconfig, 'get', 'configmap', cm,
         '-n', ns, '-o', 'json'],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        return

    import json as _json
    data = _json.loads(r.stdout).get('data', {})
    patched = False
    for key in ['nico-api-config.toml', 'carbide-api-config.toml']:
        if key not in data or 'allow_insecure_discovery' in data[key]:
            continue
        lines = data[key].splitlines(keepends=True)
        pos = next((i for i, l in enumerate(lines) if l.strip().startswith('[')), len(lines))
        lines.insert(pos, add)
        data[key] = ''.join(lines)
        patched = True

    if not patched:
        return

    patch = _json.dumps({'data': {k: data[k] for k in data
                                   if k in ['nico-api-config.toml', 'carbide-api-config.toml']}})
    subprocess.run(
        ['kubectl', '--kubeconfig', kubeconfig, 'patch', 'configmap', cm,
         '-n', ns, '--type=merge', '-p', patch],
        capture_output=True
    )
    subprocess.run(
        ['kubectl', '--kubeconfig', kubeconfig, 'rollout', 'restart',
         'deployment/nico-api', '-n', ns],
        capture_output=True
    )
    print('  allow_insecure_discovery patched ✓')


# ── Main ──────────────────────────────────────────────────────────────────────

def resolve_repo(cfg):
    """Resolve the nico repo path: nico_repo_folder joined onto whichever share
    root is accessible from here (Mac first, then VM)."""
    repo_folder = cfg.get('nico_repo_folder', 'infra-controller-core')
    nico_mac = cfg.get('nico_mac_folder', '')
    nico_vm  = cfg.get('nico_vm_folder', '')
    if nico_mac and Path(nico_mac).expanduser().exists():
        return str(Path(nico_mac).expanduser() / repo_folder)
    if nico_vm and Path(nico_vm).expanduser().exists():
        return str(Path(nico_vm).expanduser() / repo_folder)
    # backward compat
    return cfg.get('infra_controller_repo', '')


def main():
    p = argparse.ArgumentParser()
    p.add_argument('site')
    p.add_argument('--tag', default=None,
                   help='Image tag to deploy (overrides registry.nico_tag in site yaml)')
    p.add_argument('--skip-to', default=None,
                   help=f'Resume: skip releases BEFORE this one, deploy it and all after '
                        f'({", ".join(DEPLOY_ORDER)})')
    p.add_argument('--only', default=None,
                   help='Redeploy exactly ONE release, skip everything else')
    args = p.parse_args()

    if args.skip_to and args.only:
        print('Error: --skip-to and --only are mutually exclusive', file=sys.stderr)
        sys.exit(1)

    site_yaml, site_folder = resolve_site(args.site)
    cfg = yaml.safe_load(open(site_yaml))
    dc  = cfg['fabric']['dc_name']

    # Override tag if provided
    if args.tag:
        cfg.setdefault('registry', {})['nico_tag'] = args.tag

    sitename      = cfg.get('nico-system', {}).get('helm-values', {}).get('sitename', 'dev')
    kube_filename = cfg.get('kubeconfig', f'{dc}-{sitename}.kubeconfig.yaml')
    kubeconfig    = str(Path(site_folder) / kube_filename)
    repo          = resolve_repo(cfg)
    helm_dir      = str(Path(repo) / 'helm')
    prereqs_dir   = str(Path(repo) / 'helm-prereqs')

    chart_versions = cfg.get('chart-versions', {})

    if not Path(kubeconfig).exists():
        print(f'Error: kubeconfig not found: {kubeconfig}', file=sys.stderr)
        print('  Run deploy-dev-cp.py first.', file=sys.stderr)
        sys.exit(1)

    # ── Preflight: registry reachable and image exists ────────────────────────
    reg_host = cfg.get('registry', {}).get('host', '192.168.64.1')
    reg_port = cfg.get('registry', {}).get('port', 5000)
    registry = f'{reg_host}:{reg_port}'
    nico_tag = cfg.get('registry', {}).get('nico_tag', 'latest')
    print(f'\nPreflight: checking registry {registry} has nico:{nico_tag}...')
    # Accept EVERY manifest flavour: Docker with the containerd image store
    # (Linux hosts) pushes OCI manifests, and registry:2 answers a request
    # whose Accept lacks the OCI type with 404 "manifest unknown" — which
    # looked like "image not found" on the first Linux bring-up (20260902-#6).
    accept = ', '.join([
        'application/vnd.oci.image.manifest.v1+json',
        'application/vnd.oci.image.index.v1+json',
        'application/vnd.docker.distribution.manifest.v2+json',
        'application/vnd.docker.distribution.manifest.list.v2+json'])
    reach = subprocess.run(['curl', '-sf', '-m', '10', f'http://{registry}/v2/'],
                           capture_output=True, text=True)
    if reach.returncode != 0:
        print(f'  Error: cannot reach registry {registry} from here (curl exit '
              f'{reach.returncode})', file=sys.stderr)
        print('  ensure-registry.py starts it; from a Linux host a timeout means '
              'the firewall drops host↔registry traffic.', file=sys.stderr)
        sys.exit(1)
    r = subprocess.run(
        ['curl', '-sf', '-m', '10', '-o', '/dev/null',
         f'http://{registry}/v2/nico/manifests/{nico_tag}', '-H', f'Accept: {accept}'],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        tags = subprocess.run(['curl', '-s', '-m', '10',
                               f'http://{registry}/v2/nico/tags/list'],
                              capture_output=True, text=True).stdout.strip()
        print(f'  Error: image nico:{nico_tag} not in registry {registry}', file=sys.stderr)
        print(f'  tags present: {tags or "(none)"}', file=sys.stderr)
        print(f'  Run build-dev-nico.py (source) or deploy-nico-from-ngc.py '
              f'(NGC) to push it first.', file=sys.stderr)
        sys.exit(1)
    print(f'  registry {registry}/nico:{nico_tag} ✓')

    for flag, val in [('--skip-to', args.skip_to), ('--only', args.only)]:
        if val and val not in DEPLOY_ORDER:
            print(f'Error: unknown release "{val}" for {flag}', file=sys.stderr)
            print(f'  Valid: {", ".join(DEPLOY_ORDER)}', file=sys.stderr)
            sys.exit(1)

    if args.only:
        skip_set = set(DEPLOY_ORDER) - {args.only}
    elif args.skip_to:
        skip_set = set(DEPLOY_ORDER[:DEPLOY_ORDER.index(args.skip_to)])
    else:
        skip_set = set()

    def skip(release):
        if release in skip_set:
            print(f'  skipping {release}')
            return True
        return False

    if args.skip_to or args.only:
        preflight_skipped_prereqs(
            args.skip_to or args.only,
            cfg.get('nico-system', {}).get('vault', {}).get('mode', 'file'),
            cfg.get('nico-system', {}).get('rest', {}).get('enabled', True),
            kubeconfig)

    # Generate all values files via generate-dev-values.py
    vals_dir = Path(site_folder) / 'dev-values'
    vals_dir.mkdir(exist_ok=True)
    sys.path.insert(0, str(Path(__file__).parent))
    from generate_dev_values import generate as gen_values
    gen_values(cfg, vals_dir)
    print(f'Values generated → {vals_dir}')

    print('nico-dev — Deploy Nico')
    print(f'  site      : {site_yaml}')
    print(f'  kubeconfig: {kubeconfig}')
    print(f'  repo      : {repo}')

    # ── local-path-provisioner ────────────────────────────────────────────────
    if not skip('local-path-provisioner'):
        print('\nInstalling local-path-provisioner...')
        helm(['repo', 'add', 'containeroo', 'https://charts.containeroo.ch'], kubeconfig)
        helm(['repo', 'update', 'containeroo'], kubeconfig)
        helm(['upgrade', '--install', 'local-path-provisioner',
              'containeroo/local-path-provisioner',
              '-n', 'local-path-storage', '--create-namespace',
              '--wait'], kubeconfig)
        # Mark it the DEFAULT StorageClass: upstream manifests written for
        # kind (e.g. the rest-postgres kustomize base) omit storageClassName
        # and rely on a cluster default — without one their PVCs sit Pending
        # forever. Sole storage class on a single-node dev cluster → default.
        kubectl(['annotate', 'storageclass', 'local-path',
                 'storageclass.kubernetes.io/is-default-class=true',
                 '--overwrite'], kubeconfig)
        print('  local-path-provisioner ✓ (default StorageClass)')

    # ── cert-manager ──────────────────────────────────────────────────────────
    if not skip('cert-manager'):
        print('\nInstalling cert-manager...')
        ver = chart_versions.get('cert-manager', 'v1.17.1')
        helm(['repo', 'add', 'jetstack', 'https://charts.jetstack.io'], kubeconfig)
        helm(['upgrade', '--install', 'cert-manager', 'jetstack/cert-manager',
              '--version', ver,
              '-n', 'cert-manager', '--create-namespace',
              '--set', 'crds.enabled=true',
              '--wait'], kubeconfig)
        print('  cert-manager ✓')

    # ── vault ─────────────────────────────────────────────────────────────────
    vault_mode = cfg.get('nico-system', {}).get('vault', {}).get('mode', 'file')
    if not skip('vault'):
        print(f'\nInstalling Vault ({vault_mode} mode)...')
        helm(['repo', 'add', 'hashicorp', 'https://helm.releases.hashicorp.com'], kubeconfig)
        helm(['upgrade', '--install', 'vault', 'hashicorp/vault',
              '--version', chart_versions.get('vault', '0.25.0'),
              '-n', 'vault', '--create-namespace',
              '-f', str(vals_dir / 'vault.yaml'),
              '--wait'], kubeconfig)
        # The vault chart's statefulset uses updateStrategy OnDelete: a helm
        # upgrade rewrites the pod template but the RUNNING pod keeps the old
        # spec until deleted. Roll it if it is not on the latest revision.
        want = kubectl(['get', 'statefulset', 'vault', '-n', 'vault', '-o',
                        'jsonpath={.status.updateRevision}'],
                       kubeconfig, check=False).stdout.strip()
        have = kubectl(['get', 'pod', 'vault-0', '-n', 'vault', '-o',
                        'jsonpath={.metadata.labels.controller-revision-hash}'],
                       kubeconfig, check=False).stdout.strip()
        if want and have and want != have:
            print('  vault-0 runs an outdated spec (OnDelete strategy) — restarting it...')
            kubectl(['delete', 'pod', 'vault-0', '-n', 'vault'],
                    kubeconfig, check=False)
        print('  vault ✓')

    # Resolve vault root token (needed for nico-prereqs regardless of skip_set)
    if vault_mode == 'file':
        vault_token = ensure_vault_initialized(kubeconfig)
    else:
        vault_token = cfg.get('nico-system', {}).get('vault', {}).get('dev_root_token', 'root')
    wait_vault_ready(kubeconfig)

    # ── external-secrets ──────────────────────────────────────────────────────
    if not skip('external-secrets'):
        print('\nInstalling external-secrets...')
        helm(['repo', 'add', 'external-secrets',
              'https://charts.external-secrets.io'], kubeconfig)
        helm(['upgrade', '--install', 'external-secrets',
              'external-secrets/external-secrets',
              '--version', chart_versions.get('external-secrets', '0.14.3'),
              '-n', 'external-secrets', '--create-namespace',
              '-f', str(vals_dir / 'eso.yaml'),
              '--wait'], kubeconfig)
        print('  external-secrets ✓')

    # ── postgres-operator ─────────────────────────────────────────────────────
    if not skip('postgres-operator'):
        print('\nInstalling postgres-operator...')
        helm(['repo', 'add', 'postgres-op',
              'https://opensource.zalando.com/postgres-operator/charts/postgres-operator'],
             kubeconfig)
        helm(['upgrade', '--install', 'postgres-operator',
              'postgres-op/postgres-operator',
              '--version', chart_versions.get('postgres-operator', '1.15.1'),
              '-n', 'postgres', '--create-namespace',
              '-f', str(vals_dir / 'zalando-postgres-op.yaml'),
              '--wait'], kubeconfig)
        print('  postgres-operator ✓')

    # ── nico-prereqs ──────────────────────────────────────────────────────────
    if not skip('nico-prereqs'):
        print('\nInstalling nico-prereqs...')
        ensure_nico_namespace(kubeconfig)
        heal_stuck_release('nico-prereqs', 'nico-system', kubeconfig)
        ensure_ssh_host_key('nico-system', kubeconfig)
        helm(['upgrade', '--install', 'nico-prereqs', prereqs_dir,
              '-n', 'nico-system',
              '-f', str(vals_dir / 'nico-prereqs.yaml'),
              '--set', f'vault.token={vault_token}',
              '--wait', '--timeout', '10m'], kubeconfig)

        # Wait for vault-pki-config job to complete before proceeding
        print('  Waiting for vault-pki-config job...')
        deadline = time.time() + 300
        while time.time() < deadline:
            r = kubectl(['get', 'job', 'vault-pki-config',
                         '-n', 'nico-system',
                         '-o', 'jsonpath={.status.succeeded}'],
                        kubeconfig, check=False)
            if r.stdout.strip() == '1':
                break
            time.sleep(5)
        else:
            print('  Error: vault-pki-config job did not complete in 5m — '
                  'nico needs its PKI in place.', file=sys.stderr)
            print('  Diagnose: kubectl logs job/vault-pki-config -n nico-system',
                  file=sys.stderr)
            sys.exit(1)

        # Wait for postgres cluster to be fully ready (2/2 containers running)
        print('  Waiting for nico-pg-cluster-0 to be Ready...')
        deadline = time.time() + 300
        while time.time() < deadline:
            r = kubectl(['get', 'pod', 'nico-pg-cluster-0',
                         '-n', 'postgres',
                         '-o', 'jsonpath={.status.conditions[?(@.type=="Ready")].status}'],
                        kubeconfig, check=False)
            if r.stdout.strip() == 'True':
                break
            time.sleep(5)
        else:
            print('  Error: nico-pg-cluster-0 not Ready in 5m — deploying nico '
                  'against an unready database fails in confusing ways.',
                  file=sys.stderr)
            print('  Diagnose: kubectl describe pod nico-pg-cluster-0 -n postgres; '
                  'kubectl logs postgres-operator -n postgres', file=sys.stderr)
            sys.exit(1)

        print('  nico-prereqs ✓')

    # ── nico ──────────────────────────────────────────────────────────────────
    if not skip('nico'):
        print('\nInstalling nico...')
        ensure_nico_namespace(kubeconfig)
        heal_stuck_release('nico', 'nico-system', kubeconfig)
        helm(['upgrade', '--install', 'nico', helm_dir,
              '-n', 'nico-system',
              '-f', str(vals_dir / 'nico.yaml'),
              '--wait', '--timeout', '15m'], kubeconfig)
        patch_allow_insecure_discovery('nico-system', kubeconfig)
        print('  nico ✓')

    # ── NICo REST stack (temporal + keycloak + umbrella + site-agent) ─────────
    # Base feature: all four developer surfaces (nico-admin-cli, nico-cli,
    # gRPC API, REST API) must work. Toggle: nico-system.rest.enabled.
    rest_enabled = cfg.get('nico-system', {}).get('rest', {}).get('enabled', True)
    if not rest_enabled:
        print('\nNICo REST stack: disabled in site yaml (nico-system.rest.enabled) — skipping')
    else:
        import rest_deploy
        rest_dir    = str(Path(repo) / 'rest-api')
        prereqs_ref = str(Path(repo) / 'helm-prereqs')
        if not Path(rest_dir).is_dir():
            print(f'Error: rest-api/ not found in the nico repo ({rest_dir}) — '
                  f'REST is enabled but the checkout has no REST tree.', file=sys.stderr)
            sys.exit(1)

        if not skip('rest-postgres'):
            print('\nInstalling rest-postgres (ns + CA + issuer + temporal/keycloak DB)...')
            rest_deploy.deploy_rest_postgres(rest_dir, kubeconfig)

        if not skip('keycloak'):
            print('\nInstalling keycloak (dev IdP)...')
            rest_deploy.deploy_keycloak(prereqs_ref, kubeconfig)

        if not skip('temporal'):
            print('\nInstalling temporal...')
            heal_stuck_release('temporal', 'temporal', kubeconfig)
            rest_deploy.deploy_temporal(rest_dir, kubeconfig)

        if not skip('nico-rest'):
            print('\nInstalling nico-rest umbrella...')
            heal_stuck_release('nico-rest', 'nico-rest', kubeconfig)
            rest_deploy.deploy_nico_rest(repo, rest_dir, kubeconfig,
                                         registry, nico_tag,
                                         vals_dir / 'nico-rest-dev.yaml')

        if not skip('nico-rest-site-agent'):
            print('\nInstalling nico-rest-site-agent...')
            heal_stuck_release('nico-rest-site-agent', 'nico-rest', kubeconfig)
            s_uuid = rest_deploy.site_uuid(site_folder)
            rest_deploy.deploy_site_agent(repo, kubeconfig, registry,
                                          nico_tag, s_uuid)

    here = Path(__file__).resolve().parent
    print(f'\n{"="*55}')
    print('  Nico deployed ✓')
    # images.tag in the site yaml = what the cluster runs now
    if args.tag:
        import importlib.util
        _spec = importlib.util.spec_from_file_location(
            'site_images', Path(__file__).resolve().parent / 'site_images.py')
        _si = importlib.util.module_from_spec(_spec)
        _spec.loader.exec_module(_si)
        _si.record(site_yaml, deployed_tag=args.tag)
        print(f'  site yaml images.tag = {args.tag} ✓')
    print(f'\n  Verify:')
    print(f'    kubectl --kubeconfig {kubeconfig} get pods -n nico-system')
    if rest_enabled:
        print(f'    kubectl --kubeconfig {kubeconfig} get pods -n nico-rest')
        print(f'    kubectl --kubeconfig {kubeconfig} get pods -n temporal')
        print(f'\n  REST API (NodePort, production parity): http://<vm-ip>:30388')
    print(f'\n  Next — build and configure the CLIs (on Mac):')
    print(f'    python3 {here}/build-nico-clis.py {args.site} --install-to ~/.local/bin')
    print(f'    python3 {here}/configure-clis.py {args.site}')
    print(f'{"="*55}')


if __name__ == '__main__':
    main()
