#!/usr/bin/env python3
"""
DC Simulation — DPU Agent Simulator (sim-dpu-agent)

Simulates forge-dpu-agent for mh-dpu VMs.  In the current dc-sim, dpu_per_vm=0
so this script runs as a standalone process for testing the DPU agent workflow
without real DPU hardware.

Design: stub / config-file version (first iteration)
  - Reads a pre-computed network config JSON written by generate-nodes.py
  - Applies the config locally via ip(8) commands
  - Manages dnsmasq to serve the host VM its overlay/admin IP via DHCP
  - Reports status to stdout (gRPC call to nico-api is the next iteration)
  - Loops every 30 seconds; re-applies config idempotently each iteration
  - Shuts down cleanly on SIGTERM / SIGINT

Next iteration (gRPC polling):
  - Exchange Vault AppRole credentials for a Nico API token
  - Call GetManagedHostNetworkConfig(dpu_machine_id) via gRPC every 30s
  - Apply received config (vlan, vxlan, dnsmasq)
  - Call RecordDpuNetworkStatus(version, healthy=true)
  The gRPC version is deferred because it requires compiled proto stubs and
  SPIFFE mTLS or Vault AppRole wiring that is not yet present in the sim.

Usage:
  python3 sim-dpu-agent.py --config-file /etc/sim-dpu-agent/config.json
  python3 sim-dpu-agent.py --config-file config.json --dry-run --once

Environment variables (all optional; override config file):
  VAULT_ROLE_ID      Vault AppRole role_id  (future gRPC auth)
  VAULT_SECRET_ID    Vault AppRole secret_id
  VAULT_ADDR         Vault address
  NICO_API_ENDPOINT  nico-api gRPC endpoint (default: 7.133.1.17:1079)
  DPU_MACHINE_ID     UUID of this DPU machine in Nico

Config file format (JSON):
  {
    "dpu_machine_id":       "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "vlan_id":              200,
    "vni":                  1024500,
    "svi_ip":               "8.135.0.2",
    "svi_prefix_len":       31,
    "gateway_ip":           "8.135.0.1",
    "host_mac":             "52:54:00:04:01:01",
    "overlay_ip":           "10.0.0.5",
    "overlay_prefix_len":   24,
    "fabric_interface":     "eth1",
    "host_link_interface":  "eth2",
    "poll_interval_s":      30
  }
"""

import argparse
import json
import logging
import os
import re
import signal
import subprocess
import sys
import textwrap
import time
from pathlib import Path

# ── Logging ───────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%dT%H:%M:%S',
)
log = logging.getLogger('sim-dpu-agent')


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description='DC Simulation — DPU agent simulator (stub version)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Config file (--config-file) contains the pre-computed DPU network config
            written by generate-nodes.py.  See module docstring for JSON schema.

            Status is printed to stdout.  The next iteration will call
            RecordDpuNetworkStatus via gRPC instead.
        """),
    )
    p.add_argument('--config-file', required=True,
                   help='Path to JSON config file generated by generate-nodes.py')
    p.add_argument('--dry-run', action='store_true',
                   help='Print ip/dnsmasq commands but do not execute them')
    p.add_argument('--once', action='store_true',
                   help='Apply config once and exit (no polling loop)')
    p.add_argument('--dnsmasq-conf-dir', default='/etc/dnsmasq.d',
                   help='Directory for dnsmasq config fragment (default: /etc/dnsmasq.d)')
    p.add_argument('--log-level', default='INFO',
                   choices=['DEBUG', 'INFO', 'WARNING', 'ERROR'],
                   help='Log verbosity (default: INFO)')
    return p.parse_args()


# ── Config loading ────────────────────────────────────────────────────────────

def load_config(path):
    """Load and validate the JSON config file."""
    try:
        with open(path) as f:
            cfg = json.load(f)
    except FileNotFoundError:
        log.error('Config file not found: %s', path)
        sys.exit(1)
    except json.JSONDecodeError as e:
        log.error('Config file is not valid JSON: %s — %s', path, e)
        sys.exit(1)

    required = [
        'dpu_machine_id', 'vlan_id', 'vni',
        'svi_ip', 'svi_prefix_len', 'gateway_ip',
        'host_mac', 'overlay_ip', 'overlay_prefix_len',
        'fabric_interface', 'host_link_interface',
    ]
    missing = [k for k in required if k not in cfg]
    if missing:
        log.error('Config file missing required keys: %s', ', '.join(missing))
        sys.exit(1)

    # Apply environment variable overrides
    cfg.setdefault('poll_interval_s', 30)
    cfg.setdefault('nico_api_endpoint',
                   os.environ.get('NICO_API_ENDPOINT', '7.133.1.17:1079'))
    cfg.setdefault('dpu_machine_id',
                   os.environ.get('DPU_MACHINE_ID', cfg['dpu_machine_id']))

    # Vault credentials — stored for future gRPC iteration
    cfg['_vault_role_id']    = os.environ.get('VAULT_ROLE_ID', '')
    cfg['_vault_secret_id']  = os.environ.get('VAULT_SECRET_ID', '')
    cfg['_vault_addr']       = os.environ.get('VAULT_ADDR', '')

    return cfg


# ── Shell command helpers ─────────────────────────────────────────────────────

def run(cmd, dry_run=False, check=True, capture=False):
    """Run a shell command.  In dry-run mode, print and return success."""
    log.debug('run: %s', ' '.join(cmd))
    if dry_run:
        log.info('[DRY-RUN] %s', ' '.join(cmd))
        return subprocess.CompletedProcess(cmd, 0, stdout='', stderr='')
    kwargs = {'capture_output': True, 'text': True}
    result = subprocess.run(cmd, **kwargs)
    if check and result.returncode != 0:
        log.error('Command failed (rc=%d): %s\nstdout: %s\nstderr: %s',
                  result.returncode, ' '.join(cmd), result.stdout.strip(), result.stderr.strip())
        raise RuntimeError(f'Command failed: {" ".join(cmd)}')
    return result


def iface_exists(name):
    """Return True if a network interface exists in the kernel."""
    r = subprocess.run(['ip', 'link', 'show', name],
                       capture_output=True, text=True)
    return r.returncode == 0


def addr_on_iface(iface, addr):
    """Return True if addr (without prefix) is already assigned to iface."""
    r = subprocess.run(['ip', 'addr', 'show', 'dev', iface],
                       capture_output=True, text=True)
    return addr in r.stdout


def route_exists(prefix, via=None):
    """Return True if a route to prefix exists (optionally via a specific gateway)."""
    r = subprocess.run(['ip', 'route', 'show', prefix],
                       capture_output=True, text=True)
    if not r.stdout.strip():
        return False
    if via and via not in r.stdout:
        return False
    return True


# ── Network interface management ──────────────────────────────────────────────

def setup_vlan_interface(cfg, dry_run):
    """
    Create and configure the VLAN sub-interface on the fabric uplink.

    eth1.{vlan_id}: carries the DPU's L3 SVI (switch-virtual interface) IP
    that anchors this DPU in the fabric VPC.  This is the DPU's own IP, not
    the host VM's IP (the host VM gets its overlay IP via dnsmasq DHCP on eth2).
    """
    base  = cfg['fabric_interface']       # eth1
    vlan  = cfg['vlan_id']
    svi   = cfg['svi_ip']
    plen  = cfg['svi_prefix_len']
    vname = f'{base}.{vlan}'

    if not iface_exists(vname):
        log.info('Creating VLAN interface %s (VLAN %d on %s)', vname, vlan, base)
        run(['ip', 'link', 'add', 'link', base, 'name', vname,
             'type', 'vlan', 'id', str(vlan)], dry_run=dry_run)
        run(['ip', 'link', 'set', vname, 'up'], dry_run=dry_run)
    else:
        log.debug('VLAN interface %s already exists', vname)

    if not addr_on_iface(vname, svi):
        log.info('Assigning SVI IP %s/%d to %s', svi, plen, vname)
        run(['ip', 'addr', 'add', f'{svi}/{plen}', 'dev', vname], dry_run=dry_run)
    else:
        log.debug('SVI IP %s already on %s', svi, vname)

    return vname


def setup_vxlan_interface(cfg, dry_run):
    """
    Create the VXLAN interface for the tenant VPC.

    vxlan{vni}: VTEP on the DPU.  Local IP is the SVI IP (the DPU's fabric
    L3 address).  dstport 4789 is the IANA VXLAN port.  nolearning forces
    the control plane (EVPN / Nico) to handle MAC learning.
    """
    vni    = cfg['vni']
    svi_ip = cfg['svi_ip']
    vxname = f'vxlan{vni}'

    if not iface_exists(vxname):
        log.info('Creating VXLAN interface %s (VNI %d, local %s)', vxname, vni, svi_ip)
        run(['ip', 'link', 'add', vxname, 'type', 'vxlan',
             'id', str(vni), 'local', svi_ip,
             'dstport', '4789', 'nolearning'], dry_run=dry_run)
        run(['ip', 'link', 'set', vxname, 'up'], dry_run=dry_run)
    else:
        log.debug('VXLAN interface %s already exists', vxname)

    return vxname


def setup_default_route(cfg, dry_run):
    """
    Ensure a default route via the fabric gateway exists.

    In production this comes from BGP (FRR on the DPU stand-in learns 0.0.0.0/0
    from the leaf).  In the stub version we set it statically.
    """
    gw   = cfg['gateway_ip']
    vlan = cfg['vlan_id']
    base = cfg['fabric_interface']
    dev  = f'{base}.{vlan}'

    if not route_exists('0.0.0.0/0', via=gw):
        log.info('Adding default route via %s dev %s', gw, dev)
        run(['ip', 'route', 'add', 'default', 'via', gw, 'dev', dev],
            dry_run=dry_run, check=False)  # non-fatal: may already exist
    else:
        log.debug('Default route via %s already present', gw)


def apply_network_config(cfg, dry_run):
    """Apply the full network config (VLAN + VXLAN + default route) idempotently."""
    log.info('Applying network config for DPU machine %s', cfg['dpu_machine_id'])
    vlan_iface = setup_vlan_interface(cfg, dry_run)
    vxlan_iface = setup_vxlan_interface(cfg, dry_run)
    setup_default_route(cfg, dry_run)
    log.info('Network config applied: %s, %s', vlan_iface, vxlan_iface)


# ── dnsmasq management ────────────────────────────────────────────────────────

DNSMASQ_CONF_NAME = 'sim-dpu.conf'


def gen_dnsmasq_conf(cfg):
    """
    Generate a dnsmasq config fragment that serves the host VM its overlay IP.

    The host VM's eth0 (MAC = host_mac) is connected to the DPU's host-link
    interface (eth2).  dnsmasq listens on eth2 and hands out the overlay IP
    to the host MAC.

    This is the DPU-agent analogue of the relay container used for bare-metal
    hosts: instead of DHCP relay, the DPU runs its own dnsmasq for the single
    host VM behind it.
    """
    iface      = cfg['host_link_interface']
    host_mac   = cfg['host_mac']
    overlay_ip = cfg['overlay_ip']
    plen       = cfg['overlay_prefix_len']

    # Compute a minimal DHCP range (single address = the overlay IP)
    return textwrap.dedent(f"""\
        # sim-dpu-agent — generated dnsmasq config for managed host {cfg['dpu_machine_id']}
        # Do not edit manually; managed by sim-dpu-agent.py

        interface={iface}
        bind-interfaces
        no-hosts
        dhcp-range={iface},{overlay_ip},{overlay_ip},infinite
        dhcp-host={host_mac},{overlay_ip}
        # Subnet mask conveyed as option 1; prefix /{plen}
        dhcp-option=option:netmask,{_prefix_to_mask(plen)}
        log-dhcp
    """)


def _prefix_to_mask(prefix_len):
    """Convert an integer prefix length to dotted-decimal netmask string."""
    mask = (0xFFFFFFFF << (32 - prefix_len)) & 0xFFFFFFFF
    return '.'.join(str((mask >> shift) & 0xFF) for shift in (24, 16, 8, 0))


def write_dnsmasq_conf(cfg, conf_dir, dry_run):
    """Write dnsmasq config fragment and reload dnsmasq."""
    conf_path = Path(conf_dir) / DNSMASQ_CONF_NAME
    conf_text = gen_dnsmasq_conf(cfg)

    if dry_run:
        log.info('[DRY-RUN] Would write dnsmasq config to %s:\n%s', conf_path, conf_text)
        return

    try:
        Path(conf_dir).mkdir(parents=True, exist_ok=True)
        existing = conf_path.read_text() if conf_path.exists() else ''
        if existing == conf_text:
            log.debug('dnsmasq config unchanged at %s', conf_path)
            return
        conf_path.write_text(conf_text)
        log.info('Wrote dnsmasq config to %s', conf_path)
    except PermissionError:
        log.warning('Cannot write to %s — running as non-root? '
                    'dnsmasq config not updated.', conf_path)
        return

    # Reload dnsmasq (SIGHUP reloads config without dropping leases)
    reload_dnsmasq(dry_run)


def reload_dnsmasq(dry_run):
    """Send SIGHUP to dnsmasq to reload config, or start it if not running."""
    pid_path = Path('/var/run/dnsmasq.pid')
    if pid_path.exists():
        try:
            pid = int(pid_path.read_text().strip())
            run(['kill', '-HUP', str(pid)], dry_run=dry_run, check=False)
            log.info('Sent SIGHUP to dnsmasq (pid %d)', pid)
            return
        except (ValueError, FileNotFoundError):
            pass

    # dnsmasq not running — start it.  In a real DPU this would be a systemd unit.
    log.info('dnsmasq not running — starting it')
    run(['dnsmasq', '--conf-dir=/etc/dnsmasq.d', '--no-daemon', '--keep-in-foreground',
         '--pid-file=/var/run/dnsmasq.pid'],
        dry_run=dry_run, check=False)


# ── Status reporting ──────────────────────────────────────────────────────────

# In the next iteration this will call RecordDpuNetworkStatus via gRPC.
# For the stub version, status is printed to stdout so the caller (deploy
# script or test harness) can observe it.

def report_status(cfg, healthy, version=1, message=''):
    """Report DPU network status.  Stub: prints to stdout (gRPC is next step)."""
    status = {
        'dpu_machine_id': cfg['dpu_machine_id'],
        'healthy':         healthy,
        'version':         version,
        'vlan_id':         cfg['vlan_id'],
        'vni':             cfg['vni'],
        'svi_ip':          cfg['svi_ip'],
        'overlay_ip':      cfg['overlay_ip'],
        'message':         message,
        # TODO (next iteration): call nico-api.RecordDpuNetworkStatus via gRPC
        # endpoint = cfg['nico_api_endpoint']
    }
    log.info('STATUS: %s', json.dumps(status))


# ── Signal handling ───────────────────────────────────────────────────────────

_shutdown = False


def _handle_signal(signum, frame):
    global _shutdown
    log.info('Received signal %d — shutting down gracefully', signum)
    _shutdown = True


# ── Main loop ─────────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    log.setLevel(getattr(logging, args.log_level))

    cfg = load_config(args.config_file)

    log.info('sim-dpu-agent starting')
    log.info('  DPU machine ID  : %s', cfg['dpu_machine_id'])
    log.info('  VLAN            : %d', cfg['vlan_id'])
    log.info('  VNI             : %d', cfg['vni'])
    log.info('  SVI IP          : %s/%d', cfg['svi_ip'], cfg['svi_prefix_len'])
    log.info('  Overlay IP      : %s/%d', cfg['overlay_ip'], cfg['overlay_prefix_len'])
    log.info('  Fabric iface    : %s', cfg['fabric_interface'])
    log.info('  Host-link iface : %s', cfg['host_link_interface'])
    log.info('  Poll interval   : %ds', cfg['poll_interval_s'])
    log.info('  nico-api ep     : %s  (unused in stub version)', cfg['nico_api_endpoint'])
    if args.dry_run:
        log.info('  Mode            : DRY-RUN (no changes applied)')
    if cfg.get('_vault_role_id'):
        log.info('  Vault role_id   : %s (stored for next iteration)',
                 cfg['_vault_role_id'][:8] + '...')

    # Register signal handlers for clean shutdown
    signal.signal(signal.SIGTERM, _handle_signal)
    signal.signal(signal.SIGINT,  _handle_signal)

    iteration = 0
    while not _shutdown:
        iteration += 1
        log.info('--- Iteration %d ---', iteration)
        try:
            apply_network_config(cfg, args.dry_run)
            write_dnsmasq_conf(cfg, args.dnsmasq_conf_dir, args.dry_run)
            report_status(cfg, healthy=True, version=iteration)
        except Exception as exc:
            log.error('Error applying config: %s', exc)
            report_status(cfg, healthy=False, version=iteration, message=str(exc))

        if args.once:
            log.info('--once flag set — exiting after first iteration')
            break

        # Sleep in short increments so SIGTERM is handled promptly
        deadline = time.monotonic() + cfg['poll_interval_s']
        while not _shutdown and time.monotonic() < deadline:
            time.sleep(1)

    log.info('sim-dpu-agent stopped')


if __name__ == '__main__':
    main()
